/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Built In Detroit Project Contributors. All rights reserved.
 *  Licensed under the Apache 2.0 License.
 *--------------------------------------------------------------------------------------------*/

// NOTE: The 'mapping.json' file is generated by the build process and it
// should not be edited manually. This file is tracked by the VCS.
export { default as glyphCodepointsMapping } from './mapping.json' assert { type: 'json' };
